version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_PORT=8000
      - APP_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
